name: Deploy Website to Live Host

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy Build
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔧 Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install Dependencies & Build
        run: |
          npm install
          npm run build

      - name: 🚀 Sync Files via LFTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -c "set ftp:ssl-allow false; set net:timeout 15; set net:max-retries 3; open -u \"$FTP_USER\",\"$FTP_PASS\" \"$FTP_SERVER\"; mirror --reverse --verbose ./dist/ ./; quit"
